name: Building

on: [push, workflow_dispatch]

jobs:
  buildPlugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew dummyPlugin:publishToMavenLocal
          
  buildTestProject:
    runs-on: ubuntu-latest
    needs: buildPlugin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build test project
        run: |
          chmod +x gradlew
          ./gradlew modName:nmpCopyBuildRelease --stacktrace
